# Ø§Ù„Ù…Ù„Ù: render.yaml (Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ Ù„Ø¶Ù…Ø§Ù† ØªÙ†ØµÙŠØ¨ Chrome)

services:
- type: web
  name: delivery-bot-service
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python bot.py
  plan: free
  # ğŸ”´ Ø¥Ø¶Ø§ÙØ© Buildpacks Ù‡Ù†Ø§
  autoDeploy: true
  envVars:
    - key: TELEGRAM_TOKEN
      sync: false
    - key: WEB_USERNAME
      sync: false
    - key: WEB_PASSWORD
      sync: false
    - key: URL
      sync: false
  # ğŸ”´ Ø£Ù…Ø± ØªØ«Ø¨ÙŠØª Ø§Ù„Ù…ØªØµÙØ­Ø§Øª Ù‡Ù†Ø§ (Google Chrome)
  buildpacks:
    - url: https://github.com/heroku/heroku-buildpack-google-chrome
